package notify

// ntfy renders a tag that happens to be an emoji shortcode as that emoji and
// everything else as a label. Mirroring a topic without this table turns
// "warning" into "#warning", which is a visible regression from the ntfy app.
//
// This is the subset ntfy's own docs call out as commonly used, plus the ones
// the stack's own publishers send. An unknown tag stays a hashtag.
var emoji = map[string]string{
	"+1":                         "👍",
	"-1":                         "👎",
	"warning":                    "⚠️",
	"rotating_light":             "🚨",
	"triangular_flag_on_post":    "🚩",
	"skull":                      "💀",
	"facepalm":                   "🤦",
	"no_entry":                   "⛔",
	"no_entry_sign":              "🚫",
	"white_check_mark":           "✅",
	"heavy_check_mark":           "✔️",
	"x":                          "❌",
	"tada":                       "🎉",
	"loudspeaker":                "📢",
	"bell":                       "🔔",
	"no_bell":                    "🔕",
	"mega":                       "📣",
	"fire":                       "🔥",
	"bug":                        "🐛",
	"robot":                      "🤖",
	"computer":                   "💻",
	"floppy_disk":                "💾",
	"package":                    "📦",
	"whale":                      "🐳",
	"rocket":                     "🚀",
	"hourglass":                  "⏳",
	"zzz":                        "💤",
	"lock":                       "🔒",
	"unlock":                     "🔓",
	"key":                        "🔑",
	"house":                      "🏠",
	"door":                       "🚪",
	"bulb":                       "💡",
	"camera":                     "📷",
	"movie_camera":               "🎥",
	"tv":                         "📺",
	"musical_note":               "🎵",
	"envelope":                   "✉️",
	"inbox_tray":                 "📥",
	"outbox_tray":                "📤",
	"chart_with_upwards_trend":   "📈",
	"chart_with_downwards_trend": "📉",
	"memo":                       "📝",
	"calendar":                   "📅",
	"alarm_clock":                "⏰",
	"battery":                    "🔋",
	"electric_plug":              "🔌",
	"satellite":                  "📡",
	"globe_with_meridians":       "🌐",
	"wrench":                     "🔧",
	"hammer":                     "🔨",
	"gear":                       "⚙️",
	"recycle":                    "♻️",
	"arrows_counterclockwise":    "🔄",
	"heavy_plus_sign":            "➕",
	"heavy_minus_sign":           "➖",
	"question":                   "❓",
	"exclamation":                "❗",
	"information_source":         "ℹ️",
	"green_circle":               "🟢",
	"yellow_circle":              "🟡",
	"red_circle":                 "🔴",
	"partying_face":              "🥳",
	"cd":                         "💿",
	"dvd":                        "📀",
	"film_projector":             "📽️",
	"books":                      "📚",
	"bookmark":                   "🔖",
	"mag":                        "🔍",
	"broom":                      "🧹",
	"sparkles":                   "✨",
	"snowflake":                  "❄️",
	"sos":                        "🆘",
	"new":                        "🆕",
	"up":                         "🆙",
	"cop":                        "👮",
	"eyes":                       "👀",
	"ear":                        "👂",
	"speech_balloon":             "💬",
	"thought_balloon":            "💭",
}

// Emoji resolves an ntfy tag to an emoji, reporting whether it is one.
func Emoji(tag string) (string, bool) {
	e, ok := emoji[tag]
	return e, ok
}
